id = "awakened"
name = "Awakened"
description = "The open source coding agent."
version = "1.0.0"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/Tlkh201313/awakening-cli-new-gen"

[agent_servers.awakened]
name = "Awakened"
icon = "./icons/awakened.svg"

[agent_servers.awakened.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/awakened/releases/download/v1.0.0/awakened-darwin-arm64.zip"
cmd = "./awakened"
args = ["acp"]

[agent_servers.awakened.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/awakened/releases/download/v1.0.0/awakened-darwin-x64.zip"
cmd = "./awakened"
args = ["acp"]

[agent_servers.awakened.targets.linux-aarch64]
archive = "https://github.com/anomalyco/awakened/releases/download/v1.0.0/awakened-linux-arm64.tar.gz"
cmd = "./awakened"
args = ["acp"]

[agent_servers.awakened.targets.linux-x86_64]
archive = "https://github.com/anomalyco/awakened/releases/download/v1.0.0/awakened-linux-x64.tar.gz"
cmd = "./awakened"
args = ["acp"]

[agent_servers.awakened.targets.windows-x86_64]
archive = "https://github.com/anomalyco/awakened/releases/download/v1.0.0/awakened-windows-x64.zip"
cmd = "./awakened.exe"
args = ["acp"]
