export const AWAKENED_CAPABILITY_IDS = {
  browser: "awakened-browser",
  research: "awakened-research",
  marketing: "awakened-marketing",
  antigravity: "awakened-antigravity",
  graphify: "awakened-graphify",
  productivity: "awakened-productivity",
  subagents: "awakened-subagents",
  superpowers: "awakened-superpowers",
  security: "awakened-security",
  devtools: "awakened-devtools",
  testing: "awakened-testing",
  codereview: "awakened-codereview",
  aws: "awakened-aws",
  docs: "awakened-docs",
  frontend: "awakened-frontend",
  context7: "awakened-context7",
  memory: "awakened-memory",
  simplify: "awakened-simplify",
  cursor: "awakened-cursor",
  composio: "awakened-composio",
  anthropic: "awakened-anthropic",
  vercel: "awakened-vercel",
  githubAwesome: "awakened-github-awesome",
  design: "awakened-design",
  taste: "awakened-taste",
  devops: "awakened-devops",
  aiMl: "awakened-ai-ml",
  mcpSkills: "awakened-mcp-skills",
  claudePlugins: "awakened-claude-plugins",
  growth: "awakened-growth",
  dtcMarketing: "awakened-dtc-marketing",
  business: "awakened-business",
  selfImprovement: "awakened-self-improvement",
  obsidian: "awakened-obsidian",
  scraper: "awakened-scraper",
} as const

export type AwakenedCapabilityId = (typeof AWAKENED_CAPABILITY_IDS)[keyof typeof AWAKENED_CAPABILITY_IDS]

export const ALL_AWAKENED_CAPABILITY_IDS: AwakenedCapabilityId[] = [
  AWAKENED_CAPABILITY_IDS.browser,
  AWAKENED_CAPABILITY_IDS.research,
  AWAKENED_CAPABILITY_IDS.marketing,
  AWAKENED_CAPABILITY_IDS.antigravity,
  AWAKENED_CAPABILITY_IDS.graphify,
  AWAKENED_CAPABILITY_IDS.productivity,
  AWAKENED_CAPABILITY_IDS.subagents,
  AWAKENED_CAPABILITY_IDS.superpowers,
  AWAKENED_CAPABILITY_IDS.security,
  AWAKENED_CAPABILITY_IDS.devtools,
  AWAKENED_CAPABILITY_IDS.testing,
  AWAKENED_CAPABILITY_IDS.codereview,
  AWAKENED_CAPABILITY_IDS.aws,
  AWAKENED_CAPABILITY_IDS.docs,
  AWAKENED_CAPABILITY_IDS.frontend,
  AWAKENED_CAPABILITY_IDS.context7,
  AWAKENED_CAPABILITY_IDS.memory,
  AWAKENED_CAPABILITY_IDS.simplify,
  AWAKENED_CAPABILITY_IDS.cursor,
  AWAKENED_CAPABILITY_IDS.composio,
  AWAKENED_CAPABILITY_IDS.anthropic,
  AWAKENED_CAPABILITY_IDS.vercel,
  AWAKENED_CAPABILITY_IDS.githubAwesome,
  AWAKENED_CAPABILITY_IDS.design,
  AWAKENED_CAPABILITY_IDS.taste,
  AWAKENED_CAPABILITY_IDS.devops,
  AWAKENED_CAPABILITY_IDS.aiMl,
  AWAKENED_CAPABILITY_IDS.mcpSkills,
  AWAKENED_CAPABILITY_IDS.claudePlugins,
  AWAKENED_CAPABILITY_IDS.growth,
  AWAKENED_CAPABILITY_IDS.dtcMarketing,
  AWAKENED_CAPABILITY_IDS.business,
  AWAKENED_CAPABILITY_IDS.selfImprovement,
  AWAKENED_CAPABILITY_IDS.obsidian,
  AWAKENED_CAPABILITY_IDS.scraper,
]
