import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const AWAKENED_EXPERIMENTAL = truthy("AWAKENED_EXPERIMENTAL")
const copy = process.env["AWAKENED_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  AWAKENED_AUTO_HEAP_SNAPSHOT: truthy("AWAKENED_AUTO_HEAP_SNAPSHOT"),
  AWAKENED_GIT_BASH_PATH: process.env["AWAKENED_GIT_BASH_PATH"],
  AWAKENED_CONFIG: process.env["AWAKENED_CONFIG"],
  AWAKENED_CONFIG_CONTENT: process.env["AWAKENED_CONFIG_CONTENT"],
  AWAKENED_DISABLE_AUTOUPDATE: truthy("AWAKENED_DISABLE_AUTOUPDATE"),
  AWAKENED_ALWAYS_NOTIFY_UPDATE: truthy("AWAKENED_ALWAYS_NOTIFY_UPDATE"),
  AWAKENED_DISABLE_PRUNE: truthy("AWAKENED_DISABLE_PRUNE"),
  AWAKENED_DISABLE_TERMINAL_TITLE: truthy("AWAKENED_DISABLE_TERMINAL_TITLE"),
  AWAKENED_SHOW_TTFD: truthy("AWAKENED_SHOW_TTFD"),
  AWAKENED_DISABLE_AUTOCOMPACT: truthy("AWAKENED_DISABLE_AUTOCOMPACT"),
  AWAKENED_DISABLE_MODELS_FETCH: truthy("AWAKENED_DISABLE_MODELS_FETCH"),
  AWAKENED_DISABLE_MOUSE: truthy("AWAKENED_DISABLE_MOUSE"),
  AWAKENED_FAKE_VCS: process.env["AWAKENED_FAKE_VCS"],
  AWAKENED_SERVER_PASSWORD: process.env["AWAKENED_SERVER_PASSWORD"],
  AWAKENED_SERVER_USERNAME: process.env["AWAKENED_SERVER_USERNAME"],

  // Experimental
  AWAKENED_EXPERIMENTAL_FILEWATCHER: Config.boolean("AWAKENED_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  AWAKENED_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("AWAKENED_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  AWAKENED_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("AWAKENED_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  AWAKENED_MODELS_URL: process.env["AWAKENED_MODELS_URL"],
  AWAKENED_MODELS_PATH: process.env["AWAKENED_MODELS_PATH"],
  AWAKENED_DB: process.env["AWAKENED_DB"],

  AWAKENED_WORKSPACE_ID: process.env["AWAKENED_WORKSPACE_ID"],
  AWAKENED_EXPERIMENTAL_WORKSPACES: AWAKENED_EXPERIMENTAL || truthy("AWAKENED_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get AWAKENED_DISABLE_PROJECT_CONFIG() {
    return truthy("AWAKENED_DISABLE_PROJECT_CONFIG")
  },
  get AWAKENED_TUI_CONFIG() {
    return process.env["AWAKENED_TUI_CONFIG"]
  },
  get AWAKENED_CONFIG_DIR() {
    return process.env["AWAKENED_CONFIG_DIR"]
  },
  get AWAKENED_PURE() {
    return truthy("AWAKENED_PURE")
  },
  get AWAKENED_PERMISSION() {
    return process.env["AWAKENED_PERMISSION"]
  },
  get AWAKENED_PLUGIN_META_FILE() {
    return process.env["AWAKENED_PLUGIN_META_FILE"]
  },
  get AWAKENED_CLIENT() {
    return process.env["AWAKENED_CLIENT"] ?? "cli"
  },
}
